<a href="https://colab.research.google.com/github/ikoghoddds-bit/Data-Science-Portfolio-C21/blob/main/Projects/Project-1/Joseph_Project_1_To_Do_List.data_clean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project 1 – To Do List

## Problem Definition

- The goal is to take customer information based on historical transaction records and predict whether or not a customer will make a transaction. This is a binary classification problem since the customer either makes a transaction, or doesn't. This project will use Naive Bayes Gaussian classification.

## Data Collection

1. Load Pandas, Numpy, and Matplotlib.

In [62]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import userdata
import os

2. Load data Train.csv from AWS S3.

In [2]:
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Project.1-Transactions/Data/Transaction.train.big.csv'
url

'https://ddc-datascience.s3.amazonaws.com/Projects/Project.1-Transactions/Data/Transaction.train.big.csv'

### Read dataframe into Pandas

In [3]:
dataframe = pd.read_csv(url)
dataframe

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,...,var_91,var_92,var_93,var_94,var_95,var_96,var_97,var_98,var_99,var_100
0,0,train_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,train_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,train_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,train_3,0.0,4.6739,22.3915,15.6015,NaN,0.0464,NaN,NaN,...,NaN,11.1077,NaN,-12.6465,NaN,NaN,NaN,NaN,NaN,14.0618
4,4,train_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,NaN,-6.3011,NaN,NaN,...,NaN,1.3921,NaN,-16.4925,NaN,NaN,NaN,NaN,NaN,14.4421
1049996,1049996,train_1049996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,NaN,3.5744,NaN,NaN,...,NaN,2.0836,NaN,-18.6168,NaN,NaN,NaN,NaN,NaN,14.0689
1049998,1049998,train_1049998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,NaN,8.1795,NaN,NaN,...,NaN,-12.1108,NaN,10.7608,NaN,NaN,NaN,NaN,NaN,14.1690

In [4]:
dataframe.head(5)

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,...,var_91,var_92,var_93,var_94,var_95,var_96,var_97,var_98,var_99,var_100
0,0,train_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,train_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,train_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,train_3,0.0,4.6739,22.3915,15.6015,NaN,0.0464,NaN,NaN,...,NaN,11.1077,NaN,-12.6465,NaN,NaN,NaN,NaN,NaN,14.0618
4,4,train_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
dataframe.tail(5)

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,...,var_91,var_92,var_93,var_94,var_95,var_96,var_97,var_98,var_99,var_100
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,NaN,-6.3011,NaN,NaN,...,NaN,1.3921,NaN,-16.4925,NaN,NaN,NaN,NaN,NaN,14.4421
1049996,1049996,train_1049996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,NaN,3.5744,NaN,NaN,...,NaN,2.0836,NaN,-18.6168,NaN,NaN,NaN,NaN,NaN,14.0689
1049998,1049998,train_1049998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,NaN,8.1795,NaN,NaN,...,NaN,-12.1108,NaN,10.7608,NaN,NaN,NaN,NaN,NaN,14.1690

In [6]:
dataframe.shape

(1050000, 104)

In [7]:
print(dataframe.isnull().sum())

Unnamed: 0          0
ID_code             0
target         870000
var_0          870000
var_1          870000
               ...
var_96        1050000
var_97        1050000
var_98        1050000
var_99        1050000
var_100        870000
Length: 104, dtype: int64

In [8]:
dataframe['target'].value_counts()

target
0.0    161960
1.0     18040
Name: count, dtype: int64

In [9]:
dataframe.duplicated().sum()

np.int64(0)

In [10]:
print(dataframe.shape)

(1050000, 104)

In [11]:
dataframe = dataframe[dataframe['target'].notna()]
print(dataframe.shape)

(180000, 104)

In [12]:
print(dataframe.columns.tolist())

# dataframe = dataframe.drop(columns=['var_91', 'var_97', 'var_98', 'var_99']) this wipped all columns with nulls and data
print(dataframe.shape)

['Unnamed: 0', 'ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4', 'var_5', 'var_6', 'var_7', 'var_8', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_14', 'var_15', 'var_16', 'var_17', 'var_18', 'var_19', 'var_20', 'var_21', 'var_22', 'var_23', 'var_24', 'var_25', 'var_26', 'var_27', 'var_28', 'var_29', 'var_30', 'var_31', 'var_32', 'var_33', 'var_34', 'var_35', 'var_36', 'var_37', 'var_38', 'var_39', 'var_40', 'var_41', 'var_42', 'var_43', 'var_44', 'var_45', 'var_46', 'var_47', 'var_48', 'var_49', 'var_50', 'var_51', 'var_52', 'var_53', 'var_54', 'var_55', 'var_56', 'var_57', 'var_58', 'var_59', 'var_60', 'var_61', 'var_62', 'var_63', 'var_64', 'var_65', 'var_66', 'var_67', 'var_68', 'var_69', 'var_70', 'var_71', 'var_72', 'var_73', 'var_74', 'var_75', 'var_76', 'var_77', 'var_78', 'var_79', 'var_80', 'var_81', 'var_82', 'var_83', 'var_84', 'var_85', 'var_86', 'var_87', 'var_88', 'var_89', 'var_90', 'var_91', 'var_92', 'var_93', 'var_94', 'var_95', 'var_96', 'var_97', 'var_98', 'var_99', 'var_100']
(180000, 104)

In [13]:
print(dataframe.columns[dataframe.isnull().all()].tolist())

['var_3', 'var_5', 'var_6', 'var_9', 'var_10', 'var_11', 'var_12', 'var_13', 'var_16', 'var_18', 'var_19', 'var_23', 'var_25', 'var_30', 'var_31', 'var_32', 'var_33', 'var_34', 'var_35', 'var_40', 'var_42', 'var_43', 'var_44', 'var_45', 'var_46', 'var_47', 'var_50', 'var_51', 'var_53', 'var_54', 'var_55', 'var_58', 'var_59', 'var_60', 'var_64', 'var_68', 'var_69', 'var_71', 'var_74', 'var_76', 'var_77', 'var_79', 'var_81', 'var_90', 'var_91', 'var_93', 'var_95', 'var_96', 'var_97', 'var_98', 'var_99']

In [14]:
print(dataframe.isnull().sum().sum())

9180000

In [15]:
print(dataframe.isnull().sum()[dataframe.isnull().sum() > 0])

var_3     180000
var_5     180000
var_6     180000
var_9     180000
var_10    180000
var_11    180000
var_12    180000
var_13    180000
var_16    180000
var_18    180000
var_19    180000
var_23    180000
var_25    180000
var_30    180000
var_31    180000
var_32    180000
var_33    180000
var_34    180000
var_35    180000
var_40    180000
var_42    180000
var_43    180000
var_44    180000
var_45    180000
var_46    180000
var_47    180000
var_50    180000
var_51    180000
var_53    180000
var_54    180000
var_55    180000
var_58    180000
var_59    180000
var_60    180000
var_64    180000
var_68    180000
var_69    180000
var_71    180000
var_74    180000
var_76    180000
var_77    180000
var_79    180000
var_81    180000
var_90    180000
var_91    180000
var_93    180000
var_95    180000
var_96    180000
var_97    180000
var_98    180000
var_99    180000
dtype: int64

In [16]:
null_cols = dataframe.columns[dataframe.isnull().all()].tolist()
dataframe = dataframe.drop(columns=null_cols)
print(f"Dropped {len(null_cols)} fully null columns")
print(dataframe.shape)

Dropped 51 fully null columns
(180000, 53)

In [17]:
print(dataframe.isnull().sum().sum())
print(dataframe.duplicated().sum())

0
0

### Data Collection

### info()

In [18]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
Index: 180000 entries, 3 to 1049999
Data columns (total 53 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  180000 non-null  int64
 1   ID_code     180000 non-null  object
 2   target      180000 non-null  float64
 3   var_0       180000 non-null  float64
 4   var_1       180000 non-null  float64
 5   var_2       180000 non-null  float64
 6   var_4       180000 non-null  float64
 7   var_7       180000 non-null  float64
 8   var_8       180000 non-null  float64
 9   var_14      180000 non-null  float64
 10  var_15      180000 non-null  float64
 11  var_17      180000 non-null  float64
 12  var_20      180000 non-null  float64
 13  var_21      180000 non-null  float64
 14  var_22      180000 non-null  float64
 15  var_24      180000 non-null  float64
 16  var_26      180000 non-null  float64
 17  var_27      180000 non-null  float64
 18  var_28      180000 non-null  float64
 19  var_29      180000 non-null  float64
 20  var_36      180000 non-null  float64
 21  var_37      180000 non-null  float64
 22  var_38      180000 non-null  float64
 23  var_39      180000 non-null  float64
 24  var_41      180000 non-null  float64
 25  var_48      180000 non-null  float64
 26  var_49      180000 non-null  float64
 27  var_52      180000 non-null  float64
 28  var_56      180000 non-null  float64
 29  var_57      180000 non-null  float64
 30  var_61      180000 non-null  float64
 31  var_62      180000 non-null  float64
 32  var_63      180000 non-null  float64
 33  var_65      180000 non-null  float64
 34  var_66      180000 non-null  float64
 35  var_67      180000 non-null  float64
 36  var_70      180000 non-null  float64
 37  var_72      180000 non-null  float64
 38  var_73      180000 non-null  float64
 39  var_75      180000 non-null  float64
 40  var_78      180000 non-null  float64
 41  var_80      180000 non-null  float64
 42  var_82      180000 non-null  float64
 43  var_83      180000 non-null  float64
 44  var_84      180000 non-null  float64
 45  var_85      180000 non-null  float64
 46  var_86      180000 non-null  float64
 47  var_87      180000 non-null  float64
 48  var_88      180000 non-null  float64
 49  var_89      180000 non-null  float64
 50  var_92      180000 non-null  float64
 51  var_94      180000 non-null  float64
 52  var_100     180000 non-null  float64
dtypes: float64(51), int64(1), object(1)
memory usage: 74.2+ MB

### describe()

In [19]:
dataframe.describe()

,Unnamed: 0,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,var_15,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
count,1.800000e+05,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,...,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000,180000.000000
mean,5.259073e+05,0.100222,7.440715,15.870166,12.735619,-0.668334,1.190419,6.813431,11.946357,2.963064,...,11.434945,3.990847,7.566953,12.756574,10.342814,1.927078,-0.746871,-3.294620,-6.727860,14.224538
std,3.031568e+05,0.300297,3.021636,3.010492,4.185923,5.968300,5.169343,0.375564,7.364523,0.369891,...,0.541385,0.198989,1.235043,9.320939,2.520602,1.476777,1.862151,7.418545,8.278554,0.171058
min,3.000000e+00,0.000000,-2.691700,6.299300,-1.018500,-22.748700,-15.194000,5.359300,-19.544300,1.851200,...,9.816900,3.320500,3.970500,-18.489700,0.427400,-3.814500,-7.280600,-29.984000,-35.211700,13.729000
25%,2.632305e+05,0.000000,5.160325,13.830400,9.664675,-4.997500,-2.571400,6.544100,6.756875,2.698400,...,11.032400,3.853700,6.618800,5.661300,8.646700,0.890000,-2.105300,-8.757925,-12.835875,14.098900
50%,5.269195e+05,0.000000,7.350950,15.934600,12.670700,-0.560300,1.194600,6.806800,11.925300,2.959900,...,11.435500,3.996000,7.628500,12.520300,10.395800,1.899700,-0.772000,-3.170950,-6.615100,14.226800
75%,7.881872e+05,0.000000,9.511125,18.061425,15.837300,3.632525,5.090450,7.070900,17.039600,3.241425,...,11.845000,4.131625,8.583800,19.461725,12.116300,2.947225,0.526925,2.043350,-0.885250,14.361800
max,1.049999e+06,1.000000,16.716500,26.079100,26.997600,18.855400,18.471400,8.309100,39.396800,4.220400,...,13.287800,4.752800,11.150600,44.363400,20.437300,8.402400,4.993900,21.236400,18.105600,14.743000

### head()

In [20]:
dataframe.head()

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
3,3,train_3,0.0,4.6739,22.3915,15.6015,0.0464,-1.9254,6.4760,21.6435,...,11.8011,3.9677,9.5382,-8.4394,5.5043,2.2732,1.6362,11.1077,-12.6465,14.0618
5,5,train_5,0.0,14.6962,18.3383,17.4788,-9.1355,-6.4882,6.0821,11.7476,...,11.8294,3.8887,8.8591,6.1482,8.5833,2.8432,1.8434,-2.0111,-3.6166,14.4520
11,11,train_11,0.0,4.4949,14.4142,13.2219,4.9140,4.0501,5.8144,18.7136,...,11.7464,4.0017,5.8179,10.4951,12.4494,2.8009,0.3394,13.9424,-15.5776,14.1222
15,15,train_15,0.0,4.9657,16.2867,17.9579,0.6017,-5.4904,6.6670,8.1019,...,11.5481,3.9809,8.2247,21.2257,6.9931,3.3939,-2.3905,3.7943,5.6184,14.0619
19,19,train_19,0.0,9.4287,18.7822,10.7630,-0.7532,8.8477,6.8045,19.0069,...,10.8981,4.1808,9.4220,1.8563,10.5738,1.2409,-1.3888,-5.6677,-1.8961,14.0275

### tail()

In [21]:
dataframe.tail()

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
1049990,1049990,train_1049990,0.0,7.9632,20.4650,10.7295,2.9322,5.0267,7.1953,10.0695,...,12.1000,4.2019,7.1249,14.6591,10.2705,3.5833,2.5588,10.4219,-19.7158,14.0582
1049993,1049993,train_1049993,0.0,5.0862,14.4785,17.3709,-2.4732,-2.5987,6.6798,3.0420,...,10.9960,3.9637,8.0217,11.0449,9.3100,1.0545,-2.8770,-2.8052,-13.7290,14.3794
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,-6.3011,-6.8112,7.3226,14.9182,...,11.2265,3.8431,8.2748,-7.8464,9.9774,1.7377,-1.7942,1.3921,-16.4925,14.4421
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,3.5744,1.6614,6.1486,12.0996,...,10.5067,4.0642,8.3381,17.9081,12.3357,2.6530,-1.2359,2.0836,-18.6168,14.0689
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,8.1795,-5.5755,6.3705,5.1813,...,12.0632,3.8415,6.3466,30.6304,10.7439,-0.1808,0.2578,-12.1108,10.7608,14.1690

### target value_counts()

In [22]:
dataframe["target"].value_counts()

target
0.0    161960
1.0     18040
Name: count, dtype: int64

In [23]:
dataframe["target"].value_counts(dropna = False)

target
0.0    161960
1.0     18040
Name: count, dtype: int64

***"target" contains, 0s, 1s and 870000 NaNs***

### isnull()/isna()

In [24]:
dataframe.isnull().sum()*100

Unnamed: 0    0
ID_code       0
target        0
var_0         0
var_1         0
var_2         0
var_4         0
var_7         0
var_8         0
var_14        0
var_15        0
var_17        0
var_20        0
var_21        0
var_22        0
var_24        0
var_26        0
var_27        0
var_28        0
var_29        0
var_36        0
var_37        0
var_38        0
var_39        0
var_41        0
var_48        0
var_49        0
var_52        0
var_56        0
var_57        0
var_61        0
var_62        0
var_63        0
var_65        0
var_66        0
var_67        0
var_70        0
var_72        0
var_73        0
var_75        0
var_78        0
var_80        0
var_82        0
var_83        0
var_84        0
var_85        0
var_86        0
var_87        0
var_88        0
var_89        0
var_92        0
var_94        0
var_100       0
dtype: int64

In [25]:
dataframe.isna().sum().sort_values()

Unnamed: 0    0
ID_code       0
target        0
var_0         0
var_1         0
var_2         0
var_4         0
var_7         0
var_8         0
var_14        0
var_15        0
var_17        0
var_20        0
var_21        0
var_22        0
var_24        0
var_26        0
var_27        0
var_28        0
var_29        0
var_36        0
var_37        0
var_38        0
var_39        0
var_41        0
var_48        0
var_49        0
var_52        0
var_56        0
var_57        0
var_61        0
var_62        0
var_63        0
var_65        0
var_66        0
var_67        0
var_70        0
var_72        0
var_73        0
var_75        0
var_78        0
var_80        0
var_82        0
var_83        0
var_84        0
var_85        0
var_86        0
var_87        0
var_88        0
var_89        0
var_92        0
var_94        0
var_100       0
dtype: int64

### shape

In [26]:
dataframe.shape

(180000, 53)

### size

In [27]:
dataframe.size

9540000

### nunique()

In [28]:
nunique = dataframe.nunique().sort_values(ascending = False)
nunique

Unnamed: 0    180000
ID_code       180000
var_52        137280
var_86        134537
var_94        131746
var_20        130573
var_48        130208
var_65        129702
var_78        129453
var_92        128142
var_14        127809
var_57        127689
var_41        127006
var_75        125668
var_4         119849
var_66        119476
var_70        118977
var_80        115230
var_7         114505
var_21        112328
var_38        112124
var_17        108599
var_37        108401
var_24        107417
var_27        106142
var_39        106000
var_2         104710
var_82        103081
var_72        100528
var_62         90443
var_0          89982
var_1          89845
var_29         86773
var_67         86228
var_73         85501
var_28         83117
var_26         83041
var_87         80967
var_22         76198
var_36         69951
var_89         67117
var_88         57444
var_85         48476
var_49         37907
var_63         32995
var_83         24845
var_8          19006
var_61         18053
var_15         17760
var_84         10512
var_56          9500
var_100         8479
target             2
dtype: int64

### unique()

In [29]:
dataframe['target'].unique()

array([0., 1.])

### Backup - ***Making a backup***

In [30]:
dataframe_bak01 = dataframe.copy()
dataframe_bak01

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
3,3,train_3,0.0,4.6739,22.3915,15.6015,0.0464,-1.9254,6.4760,21.6435,...,11.8011,3.9677,9.5382,-8.4394,5.5043,2.2732,1.6362,11.1077,-12.6465,14.0618
5,5,train_5,0.0,14.6962,18.3383,17.4788,-9.1355,-6.4882,6.0821,11.7476,...,11.8294,3.8887,8.8591,6.1482,8.5833,2.8432,1.8434,-2.0111,-3.6166,14.4520
11,11,train_11,0.0,4.4949,14.4142,13.2219,4.9140,4.0501,5.8144,18.7136,...,11.7464,4.0017,5.8179,10.4951,12.4494,2.8009,0.3394,13.9424,-15.5776,14.1222
15,15,train_15,0.0,4.9657,16.2867,17.9579,0.6017,-5.4904,6.6670,8.1019,...,11.5481,3.9809,8.2247,21.2257,6.9931,3.3939,-2.3905,3.7943,5.6184,14.0619
19,19,train_19,0.0,9.4287,18.7822,10.7630,-0.7532,8.8477,6.8045,19.0069,...,10.8981,4.1808,9.4220,1.8563,10.5738,1.2409,-1.3888,-5.6677,-1.8961,14.0275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049990,1049990,train_1049990,0.0,7.9632,20.4650,10.7295,2.9322,5.0267,7.1953,10.0695,...,12.1000,4.2019,7.1249,14.6591,10.2705,3.5833,2.5588,10.4219,-19.7158,14.0582
1049993,1049993,train_1049993,0.0,5.0862,14.4785,17.3709,-2.4732,-2.5987,6.6798,3.0420,...,10.9960,3.9637,8.0217,11.0449,9.3100,1.0545,-2.8770,-2.8052,-13.7290,14.3794
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,-6.3011,-6.8112,7.3226,14.9182,...,11.2265,3.8431,8.2748,-7.8464,9.9774,1.7377,-1.7942,1.3921,-16.4925,14.4421
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,3.5744,1.6614,6.1486,12.0996,...,10.5067,4.0642,8.3381,17.9081,12.3357,2.6530,-1.2359,2.0836,-18.6168,14.0689
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,8.1795,-5.5755,6.3705,5.1813,...,12.0632,3.8415,6.3466,30.6304,10.7439,-0.1808,0.2578,-12.1108,10.7608,14.1690

## Data Cleaning

4. Examine the data using tools we have used in class.

### Scanning dataframe and dropping all "nulls" in the dataframe

In [31]:
dataframe_bak01.columns.to_list()

['Unnamed: 0',
 'ID_code',
 'target',
 'var_0',
 'var_1',
 'var_2',
 'var_4',
 'var_7',
 'var_8',
 'var_14',
 'var_15',
 'var_17',
 'var_20',
 'var_21',
 'var_22',
 'var_24',
 'var_26',
 'var_27',
 'var_28',
 'var_29',
 'var_36',
 'var_37',
 'var_38',
 'var_39',
 'var_41',
 'var_48',
 'var_49',
 'var_52',
 'var_56',
 'var_57',
 'var_61',
 'var_62',
 'var_63',
 'var_65',
 'var_66',
 'var_67',
 'var_70',
 'var_72',
 'var_73',
 'var_75',
 'var_78',
 'var_80',
 'var_82',
 'var_83',
 'var_84',
 'var_85',
 'var_86',
 'var_87',
 'var_88',
 'var_89',
 'var_92',
 'var_94',
 'var_100']

In [32]:
dataframe_bak01.columns

Index(['Unnamed: 0', 'ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_4',
       'var_7', 'var_8', 'var_14', 'var_15', 'var_17', 'var_20', 'var_21',
       'var_22', 'var_24', 'var_26', 'var_27', 'var_28', 'var_29', 'var_36',
       'var_37', 'var_38', 'var_39', 'var_41', 'var_48', 'var_49', 'var_52',
       'var_56', 'var_57', 'var_61', 'var_62', 'var_63', 'var_65', 'var_66',
       'var_67', 'var_70', 'var_72', 'var_73', 'var_75', 'var_78', 'var_80',
       'var_82', 'var_83', 'var_84', 'var_85', 'var_86', 'var_87', 'var_88',
       'var_89', 'var_92', 'var_94', 'var_100'],
      dtype='object')

### Scanning dataframe and dropping "nulls" in specified columns and deleting those rows

In [33]:
dataframe_bak01.dropna(subset = ['target'])

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
3,3,train_3,0.0,4.6739,22.3915,15.6015,0.0464,-1.9254,6.4760,21.6435,...,11.8011,3.9677,9.5382,-8.4394,5.5043,2.2732,1.6362,11.1077,-12.6465,14.0618
5,5,train_5,0.0,14.6962,18.3383,17.4788,-9.1355,-6.4882,6.0821,11.7476,...,11.8294,3.8887,8.8591,6.1482,8.5833,2.8432,1.8434,-2.0111,-3.6166,14.4520
11,11,train_11,0.0,4.4949,14.4142,13.2219,4.9140,4.0501,5.8144,18.7136,...,11.7464,4.0017,5.8179,10.4951,12.4494,2.8009,0.3394,13.9424,-15.5776,14.1222
15,15,train_15,0.0,4.9657,16.2867,17.9579,0.6017,-5.4904,6.6670,8.1019,...,11.5481,3.9809,8.2247,21.2257,6.9931,3.3939,-2.3905,3.7943,5.6184,14.0619
19,19,train_19,0.0,9.4287,18.7822,10.7630,-0.7532,8.8477,6.8045,19.0069,...,10.8981,4.1808,9.4220,1.8563,10.5738,1.2409,-1.3888,-5.6677,-1.8961,14.0275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049990,1049990,train_1049990,0.0,7.9632,20.4650,10.7295,2.9322,5.0267,7.1953,10.0695,...,12.1000,4.2019,7.1249,14.6591,10.2705,3.5833,2.5588,10.4219,-19.7158,14.0582
1049993,1049993,train_1049993,0.0,5.0862,14.4785,17.3709,-2.4732,-2.5987,6.6798,3.0420,...,10.9960,3.9637,8.0217,11.0449,9.3100,1.0545,-2.8770,-2.8052,-13.7290,14.3794
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,-6.3011,-6.8112,7.3226,14.9182,...,11.2265,3.8431,8.2748,-7.8464,9.9774,1.7377,-1.7942,1.3921,-16.4925,14.4421
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,3.5744,1.6614,6.1486,12.0996,...,10.5067,4.0642,8.3381,17.9081,12.3357,2.6530,-1.2359,2.0836,-18.6168,14.0689
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,8.1795,-5.5755,6.3705,5.1813,...,12.0632,3.8415,6.3466,30.6304,10.7439,-0.1808,0.2578,-12.1108,10.7608,14.1690

### Working from Backup file now to actually drop "nulls"in the dataset.

In [34]:
dataframe_bak01.dropna(subset = ['target'], inplace = True)
dataframe_bak01

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
3,3,train_3,0.0,4.6739,22.3915,15.6015,0.0464,-1.9254,6.4760,21.6435,...,11.8011,3.9677,9.5382,-8.4394,5.5043,2.2732,1.6362,11.1077,-12.6465,14.0618
5,5,train_5,0.0,14.6962,18.3383,17.4788,-9.1355,-6.4882,6.0821,11.7476,...,11.8294,3.8887,8.8591,6.1482,8.5833,2.8432,1.8434,-2.0111,-3.6166,14.4520
11,11,train_11,0.0,4.4949,14.4142,13.2219,4.9140,4.0501,5.8144,18.7136,...,11.7464,4.0017,5.8179,10.4951,12.4494,2.8009,0.3394,13.9424,-15.5776,14.1222
15,15,train_15,0.0,4.9657,16.2867,17.9579,0.6017,-5.4904,6.6670,8.1019,...,11.5481,3.9809,8.2247,21.2257,6.9931,3.3939,-2.3905,3.7943,5.6184,14.0619
19,19,train_19,0.0,9.4287,18.7822,10.7630,-0.7532,8.8477,6.8045,19.0069,...,10.8981,4.1808,9.4220,1.8563,10.5738,1.2409,-1.3888,-5.6677,-1.8961,14.0275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049990,1049990,train_1049990,0.0,7.9632,20.4650,10.7295,2.9322,5.0267,7.1953,10.0695,...,12.1000,4.2019,7.1249,14.6591,10.2705,3.5833,2.5588,10.4219,-19.7158,14.0582
1049993,1049993,train_1049993,0.0,5.0862,14.4785,17.3709,-2.4732,-2.5987,6.6798,3.0420,...,10.9960,3.9637,8.0217,11.0449,9.3100,1.0545,-2.8770,-2.8052,-13.7290,14.3794
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,-6.3011,-6.8112,7.3226,14.9182,...,11.2265,3.8431,8.2748,-7.8464,9.9774,1.7377,-1.7942,1.3921,-16.4925,14.4421
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,3.5744,1.6614,6.1486,12.0996,...,10.5067,4.0642,8.3381,17.9081,12.3357,2.6530,-1.2359,2.0836,-18.6168,14.0689
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,8.1795,-5.5755,6.3705,5.1813,...,12.0632,3.8415,6.3466,30.6304,10.7439,-0.1808,0.2578,-12.1108,10.7608,14.1690

In [35]:
dataframe_bak01.shape

(180000, 53)

In [36]:
dataframe_bak01.isnull().sum()*1000

Unnamed: 0    0
ID_code       0
target        0
var_0         0
var_1         0
var_2         0
var_4         0
var_7         0
var_8         0
var_14        0
var_15        0
var_17        0
var_20        0
var_21        0
var_22        0
var_24        0
var_26        0
var_27        0
var_28        0
var_29        0
var_36        0
var_37        0
var_38        0
var_39        0
var_41        0
var_48        0
var_49        0
var_52        0
var_56        0
var_57        0
var_61        0
var_62        0
var_63        0
var_65        0
var_66        0
var_67        0
var_70        0
var_72        0
var_73        0
var_75        0
var_78        0
var_80        0
var_82        0
var_83        0
var_84        0
var_85        0
var_86        0
var_87        0
var_88        0
var_89        0
var_92        0
var_94        0
var_100       0
dtype: int64

In [37]:
dataframe_bak01.isnull().sum().sort_values()

Unnamed: 0    0
ID_code       0
target        0
var_0         0
var_1         0
var_2         0
var_4         0
var_7         0
var_8         0
var_14        0
var_15        0
var_17        0
var_20        0
var_21        0
var_22        0
var_24        0
var_26        0
var_27        0
var_28        0
var_29        0
var_36        0
var_37        0
var_38        0
var_39        0
var_41        0
var_48        0
var_49        0
var_52        0
var_56        0
var_57        0
var_61        0
var_62        0
var_63        0
var_65        0
var_66        0
var_67        0
var_70        0
var_72        0
var_73        0
var_75        0
var_78        0
var_80        0
var_82        0
var_83        0
var_84        0
var_85        0
var_86        0
var_87        0
var_88        0
var_89        0
var_92        0
var_94        0
var_100       0
dtype: int64

In [38]:
dataframe_bak01.shape

(180000, 53)

In [39]:
dataframe_bak01.dropna(axis='columns')

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
3,3,train_3,0.0,4.6739,22.3915,15.6015,0.0464,-1.9254,6.4760,21.6435,...,11.8011,3.9677,9.5382,-8.4394,5.5043,2.2732,1.6362,11.1077,-12.6465,14.0618
5,5,train_5,0.0,14.6962,18.3383,17.4788,-9.1355,-6.4882,6.0821,11.7476,...,11.8294,3.8887,8.8591,6.1482,8.5833,2.8432,1.8434,-2.0111,-3.6166,14.4520
11,11,train_11,0.0,4.4949,14.4142,13.2219,4.9140,4.0501,5.8144,18.7136,...,11.7464,4.0017,5.8179,10.4951,12.4494,2.8009,0.3394,13.9424,-15.5776,14.1222
15,15,train_15,0.0,4.9657,16.2867,17.9579,0.6017,-5.4904,6.6670,8.1019,...,11.5481,3.9809,8.2247,21.2257,6.9931,3.3939,-2.3905,3.7943,5.6184,14.0619
19,19,train_19,0.0,9.4287,18.7822,10.7630,-0.7532,8.8477,6.8045,19.0069,...,10.8981,4.1808,9.4220,1.8563,10.5738,1.2409,-1.3888,-5.6677,-1.8961,14.0275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049990,1049990,train_1049990,0.0,7.9632,20.4650,10.7295,2.9322,5.0267,7.1953,10.0695,...,12.1000,4.2019,7.1249,14.6591,10.2705,3.5833,2.5588,10.4219,-19.7158,14.0582
1049993,1049993,train_1049993,0.0,5.0862,14.4785,17.3709,-2.4732,-2.5987,6.6798,3.0420,...,10.9960,3.9637,8.0217,11.0449,9.3100,1.0545,-2.8770,-2.8052,-13.7290,14.3794
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,-6.3011,-6.8112,7.3226,14.9182,...,11.2265,3.8431,8.2748,-7.8464,9.9774,1.7377,-1.7942,1.3921,-16.4925,14.4421
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,3.5744,1.6614,6.1486,12.0996,...,10.5067,4.0642,8.3381,17.9081,12.3357,2.6530,-1.2359,2.0836,-18.6168,14.0689
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,8.1795,-5.5755,6.3705,5.1813,...,12.0632,3.8415,6.3466,30.6304,10.7439,-0.1808,0.2578,-12.1108,10.7608,14.1690

In [40]:
dataframe_bak01.shape

(180000, 53)

In [41]:
dataframe_bak01.dropna(axis='columns', how = 'all')

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
3,3,train_3,0.0,4.6739,22.3915,15.6015,0.0464,-1.9254,6.4760,21.6435,...,11.8011,3.9677,9.5382,-8.4394,5.5043,2.2732,1.6362,11.1077,-12.6465,14.0618
5,5,train_5,0.0,14.6962,18.3383,17.4788,-9.1355,-6.4882,6.0821,11.7476,...,11.8294,3.8887,8.8591,6.1482,8.5833,2.8432,1.8434,-2.0111,-3.6166,14.4520
11,11,train_11,0.0,4.4949,14.4142,13.2219,4.9140,4.0501,5.8144,18.7136,...,11.7464,4.0017,5.8179,10.4951,12.4494,2.8009,0.3394,13.9424,-15.5776,14.1222
15,15,train_15,0.0,4.9657,16.2867,17.9579,0.6017,-5.4904,6.6670,8.1019,...,11.5481,3.9809,8.2247,21.2257,6.9931,3.3939,-2.3905,3.7943,5.6184,14.0619
19,19,train_19,0.0,9.4287,18.7822,10.7630,-0.7532,8.8477,6.8045,19.0069,...,10.8981,4.1808,9.4220,1.8563,10.5738,1.2409,-1.3888,-5.6677,-1.8961,14.0275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049990,1049990,train_1049990,0.0,7.9632,20.4650,10.7295,2.9322,5.0267,7.1953,10.0695,...,12.1000,4.2019,7.1249,14.6591,10.2705,3.5833,2.5588,10.4219,-19.7158,14.0582
1049993,1049993,train_1049993,0.0,5.0862,14.4785,17.3709,-2.4732,-2.5987,6.6798,3.0420,...,10.9960,3.9637,8.0217,11.0449,9.3100,1.0545,-2.8770,-2.8052,-13.7290,14.3794
1049995,1049995,train_1049995,1.0,11.3251,16.4148,20.5955,-6.3011,-6.8112,7.3226,14.9182,...,11.2265,3.8431,8.2748,-7.8464,9.9774,1.7377,-1.7942,1.3921,-16.4925,14.4421
1049997,1049997,train_1049997,0.0,8.9941,13.4127,3.9567,3.5744,1.6614,6.1486,12.0996,...,10.5067,4.0642,8.3381,17.9081,12.3357,2.6530,-1.2359,2.0836,-18.6168,14.0689
1049999,1049999,train_1049999,0.0,2.1828,12.3805,17.5654,8.1795,-5.5755,6.3705,5.1813,...,12.0632,3.8415,6.3466,30.6304,10.7439,-0.1808,0.2578,-12.1108,10.7608,14.1690

In [42]:
dataframe_bak01.dropna(axis='columns', how = 'all', inplace = True)

In [43]:
dataframe_bak01.shape

(180000, 53)

Size

In [44]:
dataframe_bak01.size

9540000

5. If there are data cleaning issues, develop recommendations for how to deal with them.

In [47]:
dataframe_bak01.head()

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
3,3,train_3,0.0,4.6739,22.3915,15.6015,0.0464,-1.9254,6.4760,21.6435,...,11.8011,3.9677,9.5382,-8.4394,5.5043,2.2732,1.6362,11.1077,-12.6465,14.0618
5,5,train_5,0.0,14.6962,18.3383,17.4788,-9.1355,-6.4882,6.0821,11.7476,...,11.8294,3.8887,8.8591,6.1482,8.5833,2.8432,1.8434,-2.0111,-3.6166,14.4520
11,11,train_11,0.0,4.4949,14.4142,13.2219,4.9140,4.0501,5.8144,18.7136,...,11.7464,4.0017,5.8179,10.4951,12.4494,2.8009,0.3394,13.9424,-15.5776,14.1222
15,15,train_15,0.0,4.9657,16.2867,17.9579,0.6017,-5.4904,6.6670,8.1019,...,11.5481,3.9809,8.2247,21.2257,6.9931,3.3939,-2.3905,3.7943,5.6184,14.0619
19,19,train_19,0.0,9.4287,18.7822,10.7630,-0.7532,8.8477,6.8045,19.0069,...,10.8981,4.1808,9.4220,1.8563,10.5738,1.2409,-1.3888,-5.6677,-1.8961,14.0275

In [50]:
dataframe_bak01.drop(columns=['Unnamed: 0', 'ID_code'], inplace = True)
dataframe_bak01

,target,var_0,var_1,var_2,var_4,var_7,var_8,var_14,var_15,var_17,...,var_83,var_84,var_85,var_86,var_87,var_88,var_89,var_92,var_94,var_100
3,0.0,4.6739,22.3915,15.6015,0.0464,-1.9254,6.4760,21.6435,2.8817,11.6975,...,11.8011,3.9677,9.5382,-8.4394,5.5043,2.2732,1.6362,11.1077,-12.6465,14.0618
5,0.0,14.6962,18.3383,17.4788,-9.1355,-6.4882,6.0821,11.7476,2.2225,7.2218,...,11.8294,3.8887,8.8591,6.1482,8.5833,2.8432,1.8434,-2.0111,-3.6166,14.4520
11,0.0,4.4949,14.4142,13.2219,4.9140,4.0501,5.8144,18.7136,3.4990,4.2892,...,11.7464,4.0017,5.8179,10.4951,12.4494,2.8009,0.3394,13.9424,-15.5776,14.1222
15,0.0,4.9657,16.2867,17.9579,0.6017,-5.4904,6.6670,8.1019,2.8910,8.2374,...,11.5481,3.9809,8.2247,21.2257,6.9931,3.3939,-2.3905,3.7943,5.6184,14.0619
19,0.0,9.4287,18.7822,10.7630,-0.7532,8.8477,6.8045,19.0069,3.2771,12.6446,...,10.8981,4.1808,9.4220,1.8563,10.5738,1.2409,-1.3888,-5.6677,-1.8961,14.0275
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049990,0.0,7.9632,20.4650,10.7295,2.9322,5.0267,7.1953,10.0695,3.0732,11.0135,...,12.1000,4.2019,7.1249,14.6591,10.2705,3.5833,2.5588,10.4219,-19.7158,14.0582
1049993,0.0,5.0862,14.4785,17.3709,-2.4732,-2.5987,6.6798,3.0420,2.4057,18.2729,...,10.9960,3.9637,8.0217,11.0449,9.3100,1.0545,-2.8770,-2.8052,-13.7290,14.3794
1049995,1.0,11.3251,16.4148,20.5955,-6.3011,-6.8112,7.3226,14.9182,2.4579,14.7175,...,11.2265,3.8431,8.2748,-7.8464,9.9774,1.7377,-1.7942,1.3921,-16.4925,14.4421
1049997,0.0,8.9941,13.4127,3.9567,3.5744,1.6614,6.1486,12.0996,2.5439,10.2936,...,10.5067,4.0642,8.3381,17.9081,12.3357,2.6530,-1.2359,2.0836,-18.6168,14.0689
1049999,0.0,2.1828,12.3805,17.5654,8.1795,-5.5755,6.3705,5.1813,2.5118,10.0141,...,12.0632,3.8415,6.3466,30.6304,10.7439,-0.1808,0.2578,-12.1108,10.7608,14.1690

## Convert CSV to Parquet

In [51]:
parquet_file = "transactions.parquet"
parquet_file

'transactions.parquet'

In [52]:
dataframe_bak01.to_parquet( parquet_file, index=False)

In [53]:
!ls -l --si {parquet_file}

-rw-r--r-- 1 root root 47M Jun 22 15:12 transactions.parquet

## Verify that pandas can query the local parquet file

In [54]:
dataframe_2 = pd.read_parquet( parquet_file )
dataframe_2.shape

(180000, 51)

In [55]:
dataframe_2.iloc[:,:5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180000 entries, 0 to 179999
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   target  180000 non-null  float64
 1   var_0   180000 non-null  float64
 2   var_1   180000 non-null  float64
 3   var_2   180000 non-null  float64
 4   var_4   180000 non-null  float64
dtypes: float64(5)
memory usage: 6.9 MB

## Authenticate to Hugging Face

In [63]:
# Retrieve the token from Colab's secret manager
os.environ["HF_TOKEN"] = userdata.get('hf_token')
_ = os.environ["HF_TOKEN"]
f"{_[:5]} ... {_[-3:]}"

'hf_Tz ... uJb'

In [64]:
# Log in automatically without an interactive prompt
!hf auth login --token $HF_TOKEN

Hint: A new version of huggingface_hub (1.20.1) is available! You are using version 1.18.0.
To update, run: hf update
The token has not been saved to the git credentials helper. Pass `add_to_git_credential=True` in this function directly or `--add-to-git-credential` if using via `hf`CLI if you want to set the git credential as well.
Token is valid (permission: fineGrained).
The token `hf_token` has been saved to /root/.cache/huggingface/stored_tokens
Your token has been saved to /root/.cache/huggingface/token
Login successful.
Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

## Push to Hugging Face

In [65]:
%%capture hf_upload
%%bash

hf upload \
  --type dataset \
  JosephIkogho/Data_Science-21 \
  transactions.parquet

In [66]:
print(hf_upload.stdout)

✓ Uploaded
  url: https://huggingface.co/datasets/JosephIkogho/Data_Science-21/commit/c46c37103c561cbb79bc3b6c18bdbc29fc754d7c

## Read parquet from Hugging Face

In [67]:
# Construct the base Hugging Face URL for your dataset files
hf_url = "https://huggingface.co/datasets/JosephIkogho/Data_Science-21/resolve/main/transactions.parquet"
hf_url

'https://huggingface.co/datasets/JosephIkogho/Data_Science-21/resolve/main/transactions.parquet'

In [68]:
dataframe_3 = pd.read_parquet( hf_url )
dataframe_3.shape

(180000, 51)

In [69]:
dataframe_3.iloc[:,:5].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180000 entries, 0 to 179999
Data columns (total 5 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   target  180000 non-null  float64
 1   var_0   180000 non-null  float64
 2   var_1   180000 non-null  float64
 3   var_2   180000 non-null  float64
 4   var_4   180000 non-null  float64
dtypes: float64(5)
memory usage: 6.9 MB