<a href="https://colab.research.google.com/github/ikoghoddds-bit/Data-Science-Portfolio-C21/blob/main/Projects/Project-4/Spotify_Pass_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Project 4: Music Popularity Prediction

This project will take data features collected for songs that have been on the Top 200 Weekly (Global) charts of Spotify in 2020 & 2021. The popularity of the song will be predicted using a tree-based regression model trained on these features.

The goals for the project are:

- Minimize the cross-validated ***root mean squared error ( RMSE )*** when predicting the popularity of a new song.

- Determine the importance of the features in driving the regression result.
The project will be done using tree-based regression techniques as covered in class. The hyperparameters of the trees should be carefully selected to avoid over-fitting.

There are three main challenges for this project:

1. Determining the outcome ( i.e. target ).  There is a "popularity" column.  But other columns may or may not be more appropriate indicators of popularity.

1. Choosing appropriate predictors ( i.e. features ). When building a machine learning model, we want to make sure that we consider how the model will be ultimately used. For this project, we are predicting the popularity of a new song. Therefore, we should only include the predictors we would have for a new song. It might help to imagine that the song will not be released for several weeks.

1. Data cleaning and feature engineering. Some creative cleaning and/or feature engineering may be needed to extract useful information for prediction.

Once again, be sure to go through the whole data science process and document as such in your Jupyter notebook.

The data is available on AWS S3 at https://ddc-datascience.s3.amazonaws.com/Projects/Project.4-Spotify/Data/Spotify.csv .

## Problem Definition

- What is the Business Problem?  Often some variant of saving time, saving money, and/or making money.
*Which songs will be popular*
  - ***Ans: To predict which new songs will become popular on Spotify. By knowing this in advance, stakeholders (like music labels, artists, or streaming platforms) can save time, optimize marketing budgets, and maximize revenue by focusing resources on tracks with the highest potential.***
- What Data Science Problem is this? ( *Supervised* or Unsupervised )
  - ***Ans: This is a Supervised learning problem because the dataset includes a specific "target" or outcome variable (historical popularity data) that the model learns from to make future predictions.***
- If Supervised ...
  - How did you determine what is the target?
    - ***Ans: The target is the metric we want to predict. While there is a specific "popularity" column in the dataset, the instructions note that other columns might also serve as better or alternative indicators of a song's success.***
  - What is the Target?
    - ***Ans: Song Popularity***.
  - What statistical data type is the target: Numerical or Categorical?
    - ***Ans: The target is Numerical because popularity is typically measured as a continuous score or rank (a number), rather than a category (like "Good" or "Bad")***
  - Would this be a Classification or a *Regression* problem?
    - ***Ans: This is a Regression problem. Since the target is a continuous numerical value and the primary goal is to minimize the Root Mean Squared Error (RMSE), we are predicting an exact numerical value rather than sorting songs into discrete categories.***

##Data Collection

- Where is the data source located: local file, database, website, API, other?
  - ***Ans: The data is available on AWS S3 at***: https://ddc-datascience.s3.amazonaws.com/Projects/Project.4-Spotify/Data/Spotify.csv
- Where is the data dictionary?
  - ***Ans:The data dictionary and data information documentation can be accessed via the [RStudio Publications Spotify Dataset Documentation](https://rstudio-pubs-static.s3.amazonaws.com/905910_7f0cdad64be74075b0f0440c2fab6595.html?utm_source=chatgpt.com).***
- What tools did/would you use to get and read the data?

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
# Set the URL
url = "https://ddc-datascience.s3.amazonaws.com/Projects/Project.4-Spotify/Data/Spotify.csv"
url

'https://ddc-datascience.s3.amazonaws.com/Projects/Project.4-Spotify/Data/Spotify.csv'

### Use Pandas to read and load dataset into Notebook!

In [ ]:
df = pd.read_csv(url)
df

,Index,Highest Charting Position,Number of Times Charted,Week of Highest Charting,Song Name,Streams,Artist,Artist Followers,Song ID,Genre,...,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Tempo,Duration (ms),Valence,Chord
0,1,1,8,2021-07-23--2021-07-30,Beggin',"48,633,449",Måneskin,3377762,3Wrjm47oTz2sjIgck11l5e,"['indie rock italiano', 'italian pop']",...,0.714,0.8,-4.808,0.0504,0.127,0.359,134.002,211560,0.589,B
1,2,2,3,2021-07-23--2021-07-30,STAY (with Justin Bieber),"47,248,719",The Kid LAROI,2230022,5HCyWlXZPP0y6Gqq8TgA20,['australian hip hop'],...,0.591,0.764,-5.484,0.0483,0.0383,0.103,169.928,141806,0.478,C#/Db
2,3,1,11,2021-06-25--2021-07-02,good 4 u,"40,162,559",Olivia Rodrigo,6266514,4ZtFanR9U6ndgddUvNcjcG,['pop'],...,0.563,0.664,-5.044,0.154,0.335,0.0849,166.928,178147,0.688,A
3,4,3,5,2021-07-02--2021-07-09,Bad Habits,"37,799,456",Ed Sheeran,83293380,6PQ88X9TkUIAUIZJHW2upE,"['pop', 'uk pop']",...,0.808,0.897,-3.712,0.0348,0.0469,0.364,126.026,231041,0.591,B
4,5,5,1,2021-07-23--2021-07-30,INDUSTRY BABY (feat. Jack Harlow),"33,948,454",Lil Nas X,5473565,27NovPIUIRrOZoCHxABJwK,"['lgbtq+ hip hop', 'pop rap']",...,0.736,0.704,-7.409,0.0615,0.0203,0.0501,149.995,212000,0.894,D#/Eb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1551,1552,195,1,2019-12-27--2020-01-03,New Rules,"4,630,675",Dua Lipa,27167675,2ekn2ttSfGqwhhate0LSR0,"['dance pop', 'pop', 'uk pop']",...,0.762,0.7,-6.021,0.0694,0.00261,0.153,116.073,209320,0.608,A
1552,1553,196,1,2019-12-27--2020-01-03,Cheirosa - Ao Vivo,"4,623,030",Jorge & Mateus,15019109,2PWjKmjyTZeDpmOUa3a5da,"['sertanejo', 'sertanejo universitario']",...,0.528,0.87,-3.123,0.0851,0.24,0.333,152.37,181930,0.714,B
1553,1554,197,1,2019-12-27--2020-01-03,Havana (feat. Young Thug),"4,620,876",Camila Cabello,22698747,1rfofaqEpACxVEHIZBJe6W,"['dance pop', 'electropop', 'pop', 'post-teen ...",...,0.765,0.523,-4.333,0.03,0.184,0.132,104.988,217307,0.394,D
1554,1555,198,1,2019-12-27--2020-01-03,Surtada - Remix Brega Funk,"4,607,385","Dadá Boladão, Tati Zaqui, OIK",208630,5F8ffc8KWKNawllr5WsW0r,"['brega funk', 'funk carioca']",...,0.832,0.55,-7.026,0.0587,0.249,0.182,154.064,152784,0.881,F
1555,1556,199,1,2019-12-27--2020-01-03,Lover (Remix) [feat. Shawn Mendes],"4,595,450",Taylor Swift,42227614,3i9UVldZOE0aD0JnyfAZZ0,"['pop', 'post-teen pop']",...,0.448,0.603,-7.176,0.064,0.433,0.0862,205.272,221307,0.422,G

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1556 entries, 0 to 1555
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Index                      1556 non-null   int64
 1   Highest Charting Position  1556 non-null   int64
 2   Number of Times Charted    1556 non-null   int64
 3   Week of Highest Charting   1556 non-null   object
 4   Song Name                  1556 non-null   object
 5   Streams                    1556 non-null   object
 6   Artist                     1556 non-null   object
 7   Artist Followers           1556 non-null   object
 8   Song ID                    1556 non-null   object
 9   Genre                      1556 non-null   object
 10  Release Date               1556 non-null   object
 11  Weeks Charted              1556 non-null   object
 12  Popularity                 1556 non-null   object
 13  Danceability               1556 non-null   object
 14  Energy                     1556 non-null   object
 15  Loudness                   1556 non-null   object
 16  Speechiness                1556 non-null   object
 17  Acousticness               1556 non-null   object
 18  Liveness                   1556 non-null   object
 19  Tempo                      1556 non-null   object
 20  Duration (ms)              1556 non-null   object
 21  Valence                    1556 non-null   object
 22  Chord                      1556 non-null   object
dtypes: int64(3), object(20)
memory usage: 279.7+ KB

In [56]:
df.describe()

             Index  Highest Charting Position  Number of Times Charted
count  1556.000000                1556.000000              1556.000000
mean    778.500000                  87.744216                10.668380
std     449.322824                  58.147225                16.360546
min       1.000000                   1.000000                 1.000000
25%     389.750000                  37.000000                 1.000000
50%     778.500000                  80.000000                 4.000000
75%    1167.250000                 137.000000                12.000000
max    1556.000000                 200.000000               142.000000

In [57]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Index,1556.0,778.500000,449.322824,1.0,389.75,778.5,1167.25,1556.0
Highest Charting Position,1556.0,87.744216,58.147225,1.0,37.00,80.0,137.00,200.0
Number of Times Charted,1556.0,10.668380,16.360546,1.0,1.00,4.0,12.00,142.0

### Content length

  - How many bytes ( KB, MB, GB, TB ) is the data set?
    - ***738,124 bytes (which is approximately 738 KB or 0.74 MB)***

In [ ]:
# Look at the headers
!curl -s -I {url}

HTTP/1.1 200 OK
x-amz-id-2: oUCiuNu+rgBHQmRHiq+XlDjF5i/HRsJdPX1vrNm+ROQIrNrh6yMUIo76t42B6dGZnbj7QSmhSoQnx9hXY/Lv8bznPhE8Zyvg
x-amz-request-id: TH3YXZV4R9D97G7V
Date: Tue, 14 Jul 2026 14:49:30 GMT
Last-Modified: Wed, 04 Oct 2023 17:23:56 GMT
ETag: "65b9875b11e0d7ea03ee2af024f45e99"
x-amz-server-side-encryption: AES256
Accept-Ranges: bytes
Content-Type: text/csv
Content-Length: 738124
Server: AmazonS3

In [ ]:
# Download the file
!curl -s -O {url}

In [ ]:
# Verify
!ls -la

total 740
drwxr-xr-x 1 root root   4096 Jul 14 14:49 .
drwxr-xr-x 1 root root   4096 Jul 14 14:47 ..
drwxr-xr-x 4 root root   4096 Jun  4 13:32 .config
drwxr-xr-x 1 root root   4096 Jun  4 13:32 sample_data
-rw-r--r-- 1 root root 738124 Jul 14 14:49 Spotify.csv

In [ ]:
# Look at the field names and all 23 rows

!head -1 Spotify.csv | tr , '\n' | cat -n

     1	Index
     2	Highest Charting Position
     3	Number of Times Charted
     4	Week of Highest Charting
     5	Song Name
     6	Streams
     7	Artist
     8	Artist Followers
     9	Song ID
    10	Genre
    11	Release Date
    12	Weeks Charted
    13	Popularity
    14	Danceability
    15	Energy
    16	Loudness
    17	Speechiness
    18	Acousticness
    19	Liveness
    20	Tempo
    21	Duration (ms)
    22	Valence
    23	Chord

##Data Cleaning

- How can/did you discover how many rows?
- How can/did you discover how many columns?

In [ ]:
df.shape

(1556, 23)

In [ ]:
df.shape[0]

1556

### Checking Uniqueness

- How can/did you discover if there are any unique identifiers and how would/did you handle them?

In [ ]:
# inspecting the column names, 'Index' and 'Song ID' stand out as unique identifiers.
# 'Song ID' is a text-based code unique to each track on Spotify.

df['Song ID'].is_unique

False

In [ ]:
unique_cols = [col for col in df.columns if df[col].is_unique]
display("Columns with completely unique values:", unique_cols)

'Columns with completely unique values:'

['Index', 'Song Name', 'Streams']

In [ ]:
# DataFrame containing all column names

columns_list = [
    "Index", "Highest Charting Position", "Number of Times Charted",
    "Week of Highest Charting", "Song Name", "Streams", "Artist",
    "Artist Followers", "Song ID", "Genre", "Release Date",
    "Weeks Charted", "Popularity", "Danceability", "Energy",
    "Loudness", "Speechiness", "Acousticness", "Liveness",
    "Tempo", "Duration (ms)", "Valence", "Chord"
]

# Build a summary DataFrame
uniqueness_df = pd.DataFrame({"Column Name": columns_list})

# Check if each column in your actual dataset 'df' has entirely unique values
uniqueness_df["Unique"] = [df[col].is_unique for col in uniqueness_df["Column Name"]]

# Display the resulting table
uniqueness_df

                  Column Name  Unique
0                       Index    True
1   Highest Charting Position   False
2     Number of Times Charted   False
3    Week of Highest Charting   False
4                   Song Name    True
5                     Streams    True
6                      Artist   False
7            Artist Followers   False
8                     Song ID   False
9                       Genre   False
10               Release Date   False
11              Weeks Charted   False
12                 Popularity   False
13               Danceability   False
14                     Energy   False
15                   Loudness   False
16                Speechiness   False
17               Acousticness   False
18                   Liveness   False
19                      Tempo   False
20              Duration (ms)   False
21                    Valence   False
22                      Chord   False

- How can/did you discover if there are any nulls and how would/did you handle them?

In [ ]:
# Checking for nulls. Output shows no nulls. So not dropping any for now.

df.isnull().sum()

Index                        0
Highest Charting Position    0
Number of Times Charted      0
Week of Highest Charting     0
Song Name                    0
Streams                      0
Artist                       0
Artist Followers             0
Song ID                      0
Genre                        0
Release Date                 0
Weeks Charted                0
Popularity                   0
Danceability                 0
Energy                       0
Loudness                     0
Speechiness                  0
Acousticness                 0
Liveness                     0
Tempo                        0
Duration (ms)                0
Valence                      0
Chord                        0
dtype: int64

- If Supervised, how can/did you discover if there are any nulls in your target and how would/did you handle them?

In [28]:
# Check specifically for missing values in the target

df['Popularity'].isnull().sum()

np.int64(0)

In [38]:
# Show only the rows where at least one value is missing (NaN)

df[df.isnull().any(axis=1)]
#pd.DataFrame({"Column Name": columns_list})

Empty DataFrame
Columns: [Index, Highest Charting Position, Number of Times Charted, Week of Highest Charting, Song Name, Streams, Artist, Artist Followers, Song ID, Genre, Release Date, Weeks Charted, Popularity, Danceability, Energy, Loudness, Speechiness, Acousticness, Liveness, Tempo, Duration (ms), Valence, Chord]
Index: []

[0 rows x 23 columns]

In [35]:
# Count missing values in 'Popularity' and format as a DataFrame

missing_count = df['Popularity'].isnull().sum()

check_df = pd.DataFrame({
    "Target Column": ["Popularity"],
    "Missing Values Count": [missing_count]
})

check_df

  Target Column  Missing Values Count
0    Popularity                     0

- How can/did you discover if there are any duplicates and how would/did you handle them?

In [39]:
# Checking for duplicate rows

df.duplicated().sum()

np.int64(0)

- How can/did you discover if there are any missing values and how would/did you handle them?

In [54]:
# checking for misssing value: identical to checking for nulls

df.isna().sum()

Index                        0
Highest Charting Position    0
Number of Times Charted      0
Week of Highest Charting     0
Song Name                    0
Streams                      0
Artist                       0
Artist Followers             0
Song ID                      0
Genre                        0
Release Date                 0
Weeks Charted                0
Popularity                   0
Danceability                 0
Energy                       0
Loudness                     0
Speechiness                  0
Acousticness                 0
Liveness                     0
Tempo                        0
Duration (ms)                0
Valence                      0
Chord                        0
dtype: int64

In [42]:
# Checking for nulls and revealing columns that have fewer entries than the total 1,556 rows.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1556 entries, 0 to 1555
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Index                      1556 non-null   int64
 1   Highest Charting Position  1556 non-null   int64
 2   Number of Times Charted    1556 non-null   int64
 3   Week of Highest Charting   1556 non-null   object
 4   Song Name                  1556 non-null   object
 5   Streams                    1556 non-null   object
 6   Artist                     1556 non-null   object
 7   Artist Followers           1556 non-null   object
 8   Song ID                    1556 non-null   object
 9   Genre                      1556 non-null   object
 10  Release Date               1556 non-null   object
 11  Weeks Charted              1556 non-null   object
 12  Popularity                 1556 non-null   object
 13  Danceability               1556 non-null   object
 14  Energy                     1556 non-null   object
 15  Loudness                   1556 non-null   object
 16  Speechiness                1556 non-null   object
 17  Acousticness               1556 non-null   object
 18  Liveness                   1556 non-null   object
 19  Tempo                      1556 non-null   object
 20  Duration (ms)              1556 non-null   object
 21  Valence                    1556 non-null   object
 22  Chord                      1556 non-null   object
dtypes: int64(3), object(20)
memory usage: 279.7+ KB


- How can/did you discover if there are any nested fields and how would/did you handle them?

In [50]:
# Visually inspecting the data preview, shows nested fields.

df['Genre'].head()

0    ['indie rock italiano', 'italian pop']
1                    ['australian hip hop']
2                                   ['pop']
3                         ['pop', 'uk pop']
4             ['lgbtq+ hip hop', 'pop rap']
Name: Genre, dtype: object

In [51]:
# Creating a copy of the DataFrame to keep original data safe
df_clean_genre = df.copy()

# Using '.str.replace' with a regular expression to remove brackets and single quotes
# The pattern [\[\]'] matches '[', ']', and "'" and replaces them with an empty string ""
df_clean_genre['Genre'] = df_clean_genre['Genre'].str.replace(r"[\[\]']", "", regex=True)

# Preview the cleaned 'Genre' column alongside the Song Name
df_clean_genre[['Song Name', 'Genre']].head()

                           Song Name                             Genre
0                            Beggin'  indie rock italiano, italian pop
1          STAY (with Justin Bieber)                australian hip hop
2                           good 4 u                               pop
3                         Bad Habits                       pop, uk pop
4  INDUSTRY BABY (feat. Jack Harlow)           lgbtq+ hip hop, pop rap

## Exploratory Data Analysis

- If Supervised, what data type is your target?  What does that suggest for the type of ML process you will use?

### Target

In [58]:
# Defining our target

target = 'Highest Charting Position'
target

'Highest Charting Position'

In [59]:
# Dataframe showing target values

df[target]

0         1
1         2
2         1
3         3
4         5
       ...
1551    195
1552    196
1553    197
1554    198
1555    199
Name: Highest Charting Position, Length: 1556, dtype: int64

In [60]:
# Are there nulls/NaNs in our target?

df[target].isnull().sum()

np.int64(0)

In [61]:
# What dtype is our target?
df[target].dtype

dtype('int64')

In [67]:
df[target].describe()

count    1556.000000
mean       87.744216
std        58.147225
min         1.000000
25%        37.000000
50%        80.000000
75%       137.000000
max       200.000000
Name: Highest Charting Position, dtype: float64

## Categories

In [68]:
# Defining the features I can use BEFORE release

feature_cols = [
    'Song Name', 'Artist', 'Artist Followers', 'Genre', 'Release Date',
    'Duration (ms)', 'Chord', 'Danceability', 'Energy', 'Loudness',
    'Speechiness', 'Acousticness', 'Liveness', 'Tempo', 'Valence'
]

# Defining our target column

target_col = ['Popularity']

# Define the post-release/leakage columns to exclude

exclude_cols = [
    'Index', 'Song ID', 'Highest Charting Position', 'Number of Times Charted',
    'Week of Highest Charting', 'Streams', 'Weeks Charted'
]

In [69]:
# Feature Columns

display(feature_cols)

['Song Name',
 'Artist',
 'Artist Followers',
 'Genre',
 'Release Date',
 'Duration (ms)',
 'Chord',
 'Danceability',
 'Energy',
 'Loudness',
 'Speechiness',
 'Acousticness',
 'Liveness',
 'Tempo',
 'Valence']

In [76]:
# Creating the features DataFrame (X)

df_features = df[feature_cols]
df_features

,Song Name,Artist,Artist Followers,Genre,Release Date,Duration (ms),Chord,Danceability,Energy,Loudness,Speechiness,Acousticness,Liveness,Tempo,Valence
0,Beggin',Måneskin,3377762,"['indie rock italiano', 'italian pop']",2017-12-08,211560,B,0.714,0.8,-4.808,0.0504,0.127,0.359,134.002,0.589
1,STAY (with Justin Bieber),The Kid LAROI,2230022,['australian hip hop'],2021-07-09,141806,C#/Db,0.591,0.764,-5.484,0.0483,0.0383,0.103,169.928,0.478
2,good 4 u,Olivia Rodrigo,6266514,['pop'],2021-05-21,178147,A,0.563,0.664,-5.044,0.154,0.335,0.0849,166.928,0.688
3,Bad Habits,Ed Sheeran,83293380,"['pop', 'uk pop']",2021-06-25,231041,B,0.808,0.897,-3.712,0.0348,0.0469,0.364,126.026,0.591
4,INDUSTRY BABY (feat. Jack Harlow),Lil Nas X,5473565,"['lgbtq+ hip hop', 'pop rap']",2021-07-23,212000,D#/Eb,0.736,0.704,-7.409,0.0615,0.0203,0.0501,149.995,0.894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1551,New Rules,Dua Lipa,27167675,"['dance pop', 'pop', 'uk pop']",2017-06-02,209320,A,0.762,0.7,-6.021,0.0694,0.00261,0.153,116.073,0.608
1552,Cheirosa - Ao Vivo,Jorge & Mateus,15019109,"['sertanejo', 'sertanejo universitario']",2019-10-11,181930,B,0.528,0.87,-3.123,0.0851,0.24,0.333,152.37,0.714
1553,Havana (feat. Young Thug),Camila Cabello,22698747,"['dance pop', 'electropop', 'pop', 'post-teen ...",2018-01-12,217307,D,0.765,0.523,-4.333,0.03,0.184,0.132,104.988,0.394
1554,Surtada - Remix Brega Funk,"Dadá Boladão, Tati Zaqui, OIK",208630,"['brega funk', 'funk carioca']",2019-09-25,152784,F,0.832,0.55,-7.026,0.0587,0.249,0.182,154.064,0.881
1555,Lover (Remix) [feat. Shawn Mendes],Taylor Swift,42227614,"['pop', 'post-teen pop']",2019-11-13,221307,G,0.448,0.603,-7.176,0.064,0.433,0.0862,205.272,0.422

In [73]:
# Target Column(s)

display(target_col)

['Popularity']

In [77]:
# Create the target DataFrame/Series (y)

df_target = df[target_col]
df_target

     Popularity
0           100
1            99
2            99
3            98
4            96
...         ...
1551         79
1552         66
1553         81
1554         60
1555         70

[1556 rows x 1 columns]

In [72]:
# Excluded Column(s) for now

display(exclude_cols)

['Index',
 'Song ID',
 'Highest Charting Position',
 'Number of Times Charted',
 'Week of Highest Charting',
 'Streams',
 'Weeks Charted']

In [78]:
# Create the excluded columns DataFrame (in case I need to reference them later)

df_excluded = df[exclude_cols]
df_excluded

,Index,Song ID,Highest Charting Position,Number of Times Charted,Week of Highest Charting,Streams,Weeks Charted
0,1,3Wrjm47oTz2sjIgck11l5e,1,8,2021-07-23--2021-07-30,"48,633,449",2021-07-23--2021-07-30\n2021-07-16--2021-07-23...
1,2,5HCyWlXZPP0y6Gqq8TgA20,2,3,2021-07-23--2021-07-30,"47,248,719",2021-07-23--2021-07-30\n2021-07-16--2021-07-23...
2,3,4ZtFanR9U6ndgddUvNcjcG,1,11,2021-06-25--2021-07-02,"40,162,559",2021-07-23--2021-07-30\n2021-07-16--2021-07-23...
3,4,6PQ88X9TkUIAUIZJHW2upE,3,5,2021-07-02--2021-07-09,"37,799,456",2021-07-23--2021-07-30\n2021-07-16--2021-07-23...
4,5,27NovPIUIRrOZoCHxABJwK,5,1,2021-07-23--2021-07-30,"33,948,454",2021-07-23--2021-07-30
...,...,...,...,...,...,...,...
1551,1552,2ekn2ttSfGqwhhate0LSR0,195,1,2019-12-27--2020-01-03,"4,630,675",2019-12-27--2020-01-03
1552,1553,2PWjKmjyTZeDpmOUa3a5da,196,1,2019-12-27--2020-01-03,"4,623,030",2019-12-27--2020-01-03
1553,1554,1rfofaqEpACxVEHIZBJe6W,197,1,2019-12-27--2020-01-03,"4,620,876",2019-12-27--2020-01-03
1554,1555,5F8ffc8KWKNawllr5WsW0r,198,1,2019-12-27--2020-01-03,"4,607,385",2019-12-27--2020-01-03
1555,1556,3i9UVldZOE0aD0JnyfAZZ0,199,1,2019-12-27--2020-01-03,"4,595,450",2019-12-27--2020-01-03

### Verifying Dataframe Splits

In [79]:
# Printing Dataframe to verify that the split worked
# Be sure that I haven't missed any columns,

print("Main DataFrame shape:   ", df.shape)
print("Features DataFrame shape:", df_features.shape)
print("Target DataFrame shape:  ", df_target.shape)
print("Excluded DataFrame shape:", df_excluded.shape)

Main DataFrame shape:    (1556, 23)
Features DataFrame shape: (1556, 15)
Target DataFrame shape:   (1556, 1)
Excluded DataFrame shape: (1556, 7)

- What is the distribution of values for your target?
- How can/did you discover which fields are Categorical?
- How can/did you discover which fields are Numerical?
- For each field, what is the distribution?
- How can/did you discover the relationship between any two variables?